version: "3"

services:

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    image: hot-potato-using-nestjs-microservices/api
    build:
      context: ./services/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      HOST: 0.0.0.0
      PORT: 3001
      RMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    ports:
      - "3001:3001"

  player1:
    image: hot-potato-using-nestjs-microservices/player1
    build:
      context: ./services/player
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      HOST: 0.0.0.0
      PORT: 4001
      RMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    ports:
      - "4001:4001"

  player2:
    image: hot-potato-using-nestjs-microservices/player2
    build:
      context: ./services/player
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      HOST: 0.0.0.0
      PORT: 4002
      RMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    ports:
      - "4002:4002"

  player3:
    image: hot-potato-using-nestjs-microservices/player3
    build:
      context: ./services/player
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      PORT: 4003
      RMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    ports:
      - "4003:4003"

